# Generated by Django 5.1.5 on 2025-02-03 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_id", models.IntegerField(unique=True)),
                ("title", models.CharField(max_length=100)),
                ("color", models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chapter_id", models.IntegerField(unique=True)),
                ("title", models.CharField(max_length=100)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="chesser.course"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Variation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("variation_id", models.IntegerField(unique=True)),
                ("title", models.CharField(max_length=100)),
                ("alternative", models.BooleanField(default=False)),
                ("informational", models.BooleanField(default=False)),
                ("start_move", models.IntegerField(default=1)),
                ("end_move", models.IntegerField(default=99)),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chesser.chapter",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Move",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("move_id", models.IntegerField(unique=True)),
                ("move_num", models.IntegerField()),
                ("san", models.CharField(max_length=10)),
                ("annotation", models.CharField(blank=True, max_length=10, null=True)),
                ("text", models.TextField(blank=True, null=True)),
                (
                    "variation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chesser.variation",
                    ),
                ),
            ],
        ),
    ]
