# Generated by Django 5.1.5 on 2025-02-10 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("color", models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="chesser.course"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Variation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("alternative", models.BooleanField(default=False)),
                ("informational", models.BooleanField(default=False)),
                (
                    "start",
                    models.IntegerField(default=2, help_text="start move number"),
                ),
                ("end", models.IntegerField(default=99, help_text="end move number")),
                ("next_review", models.DateTimeField(blank=True, null=True)),
                ("next_level", models.IntegerField(default=1)),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chesser.chapter",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VariationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime", models.DateTimeField(auto_now_add=True)),
                ("level", models.IntegerField()),
                ("passed", models.BooleanField(default=False)),
                (
                    "variation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chesser.variation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Move",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("move_num", models.IntegerField()),
                ("sequence", models.IntegerField()),
                ("san", models.CharField(max_length=10)),
                ("annotation", models.CharField(blank=True, max_length=10, null=True)),
                ("text", models.TextField(blank=True, null=True)),
                ("alt", models.JSONField(default=dict)),
                ("alt_fail", models.JSONField(default=dict)),
                (
                    "variation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moves",
                        to="chesser.variation",
                    ),
                ),
            ],
            options={
                "ordering": ["sequence"],
                "unique_together": {("variation", "sequence")},
            },
        ),
    ]
