# Generated by Django 5.1.6 on 2025-03-08 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chesser", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="variation",
            name="unique_move_sequence_per_course",
        ),
        migrations.RenameField(
            model_name="variation",
            old_name="move_sequence",
            new_name="mainline_moves_str",
        ),
        migrations.AlterField(
            model_name="quizresult",
            name="variation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quiz_results",
                to="chesser.variation",
            ),
        ),
        migrations.AddConstraint(
            model_name="variation",
            constraint=models.UniqueConstraint(
                fields=("course", "mainline_moves_str"),
                name="unique_moves_string_per_course",
            ),
        ),
    ]
