# Generated by Django 5.1.7 on 2025-03-18 02:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chesser", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizresult",
            name="datetime",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="variation",
            name="level",
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name="variation",
            name="next_review",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
    ]
