# Generated by Django 5.1.7 on 2025-04-03 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chesser", "0002_add_date_and_level_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="variation",
            name="created_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
