# Generated by Django 5.1.7 on 2025-04-07 22:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chesser", "0003_variation_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variation",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
        ),
    ]
