# Generated by Django 5.1.7 on 2025-04-08 01:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chesser", "0004_alter_variation_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizresult",
            name="datetime",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now, editable=False
            ),
        ),
    ]
