# Generated by Django 5.2.1 on 2025-05-26 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chesser", "0005_alter_quizresult_datetime"),
    ]

    operations = [
        migrations.CreateModel(
            name="SharedMove",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fen", models.CharField()),
                ("san", models.CharField(max_length=10)),
                ("annotation", models.CharField(blank=True, default="", max_length=10)),
                ("text", models.TextField(blank=True, null=True)),
                ("alt", models.TextField(blank=True, null=True)),
                ("alt_fail", models.TextField(blank=True, null=True)),
                ("shapes", models.TextField(blank=True, null=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="chesser.chapter",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="chesser.course"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="move",
            name="shared_move",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="chesser.sharedmove",
            ),
        ),
        migrations.AddIndex(
            model_name="sharedmove",
            index=models.Index(
                fields=["fen", "san", "course", "chapter"],
                name="chesser_sha_fen_14a56f_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="sharedmove",
            constraint=models.UniqueConstraint(
                fields=("fen", "san", "course", "chapter"), name="unique_shared_move"
            ),
        ),
    ]
