# Generated by Django 5.2.1 on 2025-05-27 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chesser", "0006_sharedmove_move_shared_move_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="sharedmove",
            name="unique_shared_move",
        ),
        migrations.RemoveIndex(
            model_name="sharedmove",
            name="chesser_sha_fen_14a56f_idx",
        ),
        migrations.RemoveField(
            model_name="sharedmove",
            name="chapter",
        ),
        migrations.RemoveField(
            model_name="sharedmove",
            name="course",
        ),
        migrations.AlterField(
            model_name="move",
            name="shared_move",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="moves",
                to="chesser.sharedmove",
            ),
        ),
        migrations.AlterField(
            model_name="sharedmove",
            name="fen",
            field=models.CharField(db_index=True),
        ),
    ]
