# Generated by Django 5.2.1 on 2025-05-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chesser", "0007_remove_sharedmove_unique_shared_move_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="move",
            name="fen",
            field=models.CharField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="sharedmove",
            name="fen",
            field=models.CharField(blank=True, db_index=True, null=True),
        ),
    ]
