# Generated by Django 5.2.1 on 2025-05-27 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chesser", "0008_move_fen_alter_sharedmove_fen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="move",
            name="fen",
            field=models.CharField(db_index=True, default="abc"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="sharedmove",
            name="fen",
            field=models.CharField(db_index=True, default="abc"),
            preserve_default=False,
        ),
    ]
