# Generated by Django 5.2.1 on 2025-05-29 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chesser", "0009_alter_move_fen_alter_sharedmove_fen"),
    ]

    operations = [
        migrations.AddField(
            model_name="sharedmove",
            name="opening_color",
            field=models.CharField(default="white", max_length=5),
            preserve_default=False,
        ),
    ]
