# Generated by Django 5.2.1 on 2025-05-31 10:53

from django.db import migrations, models


def set_empty_strings(apps, schema_editor):
    Move = apps.get_model("chesser", "Move")
    SharedMove = apps.get_model("chesser", "SharedMove")

    for model in [Move, SharedMove]:
        model.objects.filter(alt__isnull=True).update(alt="")
        model.objects.filter(alt_fail__isnull=True).update(alt_fail="")
        model.objects.filter(shapes__isnull=True).update(shapes="")
        model.objects.filter(text__isnull=True).update(text="")


class Migration(migrations.Migration):

    dependencies = [
        ("chesser", "0010_sharedmove_opening_color"),
    ]

    operations = [
        migrations.RunPython(set_empty_strings),
        migrations.AlterField(
            model_name="move",
            name="alt",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="move",
            name="alt_fail",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="move",
            name="shapes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="move",
            name="text",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="sharedmove",
            name="alt",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="sharedmove",
            name="alt_fail",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="sharedmove",
            name="shapes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="sharedmove",
            name="text",
            field=models.TextField(blank=True, default=""),
        ),
    ]
