# Generated by Django 5.2.1 on 2025-06-04 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "chesser",
            "0011_alter_move_alt_alter_move_alt_fail_alter_move_shapes_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="variation",
            name="is_intro",
            field=models.BooleanField(default=False),
        ),
    ]
