# Generated by Django 5.2.2 on 2025-07-09 15:07

from django.db import migrations, models


def copy_course_color(apps, schema_editor):
    Chapter = apps.get_model("chesser", "Chapter")
    for chapter in Chapter.objects.select_related("course").all():
        chapter.color = chapter.course.color
        chapter.save()


class Migration(migrations.Migration):

    dependencies = [
        ("chesser", "0012_variation_is_intro"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="color",
            field=models.CharField(
                max_length=5,
                choices=[("white", "White"), ("black", "Black")],
                null=True,
            ),
        ),
        migrations.RunPython(copy_course_color, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="chapter",
            name="color",
            field=models.CharField(
                max_length=5,
                choices=[("white", "White"), ("black", "Black")],
                null=False,
            ),
        ),
    ]
