# Generated by Django 5.2.2 on 2025-07-11 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chesser", "0013_chapter_color"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="variation",
            name="unique_moves_string_per_course",
        ),
        migrations.AddConstraint(
            model_name="variation",
            constraint=models.UniqueConstraint(
                fields=("chapter", "mainline_moves_str"),
                name="unique_moves_string_per_chapter",
            ),
        ),
    ]
