# Generated by Django 5.2.2 on 2025-07-12 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chesser", "0014_remove_variation_unique_moves_string_per_course_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chapter",
            name="course",
        ),
        migrations.RemoveField(
            model_name="variation",
            name="course",
        ),
        migrations.DeleteModel(
            name="Course",
        ),
    ]
