# Generated by Django 6.0.1 on 2026-01-12 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chesser", "0015_remove_chapter_course_remove_variation_course_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variation",
            name="mainline_moves_str",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
