# Generated by Django 6.0.1 on 2026-02-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chesser", "0016_alter_variation_mainline_moves_str"),
    ]

    operations = [
        migrations.AddField(
            model_name="variation",
            name="archived",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
