# Generated by Django 6.0.2 on 2026-02-09 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chesser", "0017_variation_archived"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chapter",
            options={
                "ordering": [
                    models.Case(
                        models.When(color="white", then=models.Value(0)),
                        models.When(color="black", then=models.Value(1)),
                        default=models.Value(99),
                        output_field=models.IntegerField(),
                    ),
                    "title",
                ]
            },
        ),
    ]
